### PR TITLE
Add EntityFrameworkCore V1

### PR DESCRIPTION
**Pull request by bnemetchek**
This PR adds EntityFramework Core V1 functionality.  This has been tested with web api 2.2 and not the new asp.net core.

Working:
1. The metadata is being generated.
2.  oData functionality tested.
3.  TypeScript generators for both EF Core DbContext and Breeze metadata.

Not working:
1. Nothing that I am aware of.

Notes:
1.  When an inline count is requested, the count query is run async to improve perf.
2.  The oData expression trees, especially with null propagation, can cause perf issues.  I have added some fixups via expression visitors to correct this.  This would also be useful for EF6.
3.  EF Core 1 will fall back to client-side evaluation in too many cases.  I see this is #1 on their roadmap to improve.  When this fallback occurs, the linq expressions can fail as they are now being evaluated in a dotnet object environment vs a database environment.

### CODE REVIEW

**Comment by steveschmitt** [comment]
Wow, thanks!  We'll take a look.

**Comment by anwaramoon** [comment]
Any update on this plz? Is it likely to support .net core near future? Thx

**Comment by bnemetchek** [comment]
anwaramoon, I think it's great you've taken an interest in this.  I haven't heard back from steveschmitt on that the breeze folk are going to do with this.  It would seem that currently, the only way to use this is to download this PR's source and use the two new EF core projects in it in your projects.  Please read the caveats in my PR notes as I don't believe EF Core 1.0 is ready for prime time yet.  It looks like EF Core 1.1 has a much better chance of being useful which, according to the EF roadmap, will be available Q4/Q1.  

Good luck!

**Comment by senseiweb** [comment]
@steveschmitt @wardbell @jtraband are you guys accepting community support in porting the current code base over to the .net/ef core stack? I have few weeks between projects and would to love to try building on the work done by @bnemetchek for my first open source effort.

**Comment by steveschmitt** [comment]
We really appreciate the work being done on this.  Our plan is to do a major refactoring of the code to reduce coupling and make it easier to adapt the breeze.server.net functionality to different .NET platforms.

**Comment by steveschmitt** [comment]
Closing as we have support for .NET Core 3.1 and 5.x in the [Breeze.Persistence](https://www.nuget.org/packages?q=breeze.persistence) and [Breeze.AspNetCore](https://www.nuget.org/packages?q=breeze.aspnetcore) packages.

**Pull request closed without merging**
