### PR TITLE
Add ability to use cancellation tokens with BreezeQueryFilter

### PR DESCRIPTION
**Pull request by biegehydra**
Fixes issue #189

I think this is the best solution to the problem of cancellation tokens. They should be natively supported because the breeze client natively accepts a cancellation token as a parameter when sending a request. Telling people to use an additional filter/middleware to catch an `OperationCanceledException` is not only a klunky solution, but it's hardly even a solution. 

The problem with that approach is the exception won't be thrown until after `ToList()` has completed - it's synchronous. This means the entire database query will still run to completion in entirety, making the exception thrown after pointless. The point of a cancellation token is to stop the database query and save resources. Middleware/additional filters can't do that. To do that, you have to pass the cancellation token to `ToListAsync()`. That function is part of EF so I ported it to this project and made it internal.

I added a variable to the `BreezeQueryFilter` called `CatchCancellations` so this is an **opt in feature** and won't cause any breaking changes.

My solution uses an `IAsyncEnumerable` which isn't part of `netstandard2.0` so I only made my changes in the Dotnet projects. I feel like it should be possible for a solution to be created for AspNetCore but I couldn't find a way to do it.

#### Testing

I was not able to run the unit tests so this was only tested inside of another project. In my testing, everything works as expected. If the CatchCancellations is enabled, the cancellation is detected in ToListAsync, the process is cancelled, and database resources are saved.

### CODE REVIEW

**Comment by steveschmitt** [comment]
Thanks, great work!  I'll take a look and run some tests.

**Comment by steveschmitt** [comment]
For the async code, shouldn't we override [OnActionExecutionAsync](https://learn.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-7.0#implementation)?

**Comment by biegehydra** [comment]
For some reason I was under the impression that `IAsyncActionFilter`s couldn't be used as attributes. Turns out they can, you just inherit Attribute.

I went ahead and did the conversion and its working great. Being async also made the code a little cleaner. 

This will help all the servers that are using breeze drastically. Previously every db query was being run synchronously. This will free up the thread while the db query is running.

**Comment by steveschmitt** [comment]
Thanks again.  Will review it soon.

**Comment by steveschmitt** [comment]
I've merged the PR, after making the change I described above.

Thanks for doing this, it was very helpful.

**Comment by papadi** [comment]
I'm afraid this change removes the option to override the behavior. Previously, OnActionExecuted was overridable before. The methods aren't.

**Comment by steveschmitt** [comment]
@papadi That's a very good point!  I'll try to fix that.

**Comment by steveschmitt** [comment]
I added it as a separate issue #195

**Pull request closed without merging**
